language: php

branches:
  only:
    - master

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.7 WP_MULTISITE=0

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1

install:
  - composer install --no-interaction --no-progress --no-suggest

before_script:
  - bash ./bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpmd ./ text ./phpmd.xml.dist